services:  
  react:
    container_name: react
    build: .
    volumes:
      - react-volume:/var/www/html
  
  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs
  
  nginx:
    container_name: nginx_app
    build: ./nginx
    restart: always
    ports:
      - 8080:80
      - 443:443
    volumes:
      - react-volume:/var/www/html
      - ssl-certs:/certs
    depends_on:
      - react

volumes:
  react-volume:
  ssl-certs: